version: "3.8"
services:
    web:
        image: lyotin/demo-web
        ports:
            - 8000:80
        volumes:
            - "/projects/demo-app/web:/var/www/html:ro"
        networks:
            - app-network
        depends_on:
            - db
    db:
        image: lyotin/demo-db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
networks:
    app-network:
